version: '3.8'

services:
  db:
    image: postgres
    container_name: retailpulse-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: retailpulse
    ports:
      - "5432:5432"
  metabase:
    image: metabase/metabase
    container_name: retailpulse-metabase
    ports:
      - "3000:3000"
    depends_on:
      - db
      